name: dev-build-and-deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      DIST: build
      CI: true
    outputs:
      status: ${{ steps.tests.outcome }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: | 
          npm run build
          ls -la

      # - name: Run tests
      #   run: |
      #     npm test
      #   id: tests

      - uses: actions/upload-artifact@v2
        with:
          name: countries-and-cities
          path: build/


  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    #if: needs.tests.outputs.status == 'success'
    needs: build-and-test
    env:
      BUCKET: countries-poc.aws.cfainstitute.org
      DIST: build
      DIST_ID: E8YZLBY87OKAS
      CI: true
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: countries-and-cities
    
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Copy files to the dev s3
        run: |
          aws s3 sync --delete . s3://${{ env.BUCKET }}

      - name: cloudfront cache invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*" 

  deploy-to-test:
    name: Deploy to test
    needs: deploy-to-dev
    environment: test
    runs-on: ubuntu-latest
    env:
      BUCKET: countries-and-cities-ui
      DIST_ID: E2292YAC8N7NTD
      CI: true
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: countries-and-cities
    
      - name: Display structure of downloaded files
        run: ls -R

      - name: Copy files to the dev s3
        run: |
          aws s3 sync --delete . s3://${{ env.BUCKET }}

      - name: cloudfront cache invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"

     