name: dev-build-and-deploy
on:
  push:
    branches:
      - pipeline-test
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: countries-poc.aws.cfainstitute.org
      DIST: build
      DIST_ID: E8YZLBY87OKAS
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: | 
          npm run build
          tree

      # - name: Copy files to the dev s3
      #   run: |
      #     aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      # - name: cloudfront cache invalidation
      #   run: |
      #     aws cloudfront create-invalidation \
      #       --distribution-id ${{ env.DIST_ID }} \
      #       --paths "/*" 